name: 08 - Using Variables
on:
    push:
    workflow_dispatch:


env:
    WORKFLOW_VAR: 'I am a workflow env var'
    OVERWRITTEN: 'I will overwritten'

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'I am job var'
            OVERWRITTEN: 'I have been overwritten a the job level'
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: 'I am step env var'
                step-var2: 'I am another step var'
              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"
                echo "Step env var 2: $step-var2"
                echo "Job env var: ${{ env.JOB_VAR }}"
                echo "Workflow en var: ${{ env.WORKFLOW_VAR }}"
                echo "Overwritten var: ${{ env.OVERWRITTEN }}"
            - name: Overwritten job variable
              env:
                OVERWRITTEN: 'I have been overwritten a the step level'
              run: |
                echo "Step en var ${{  env.OVERWRITTEN }}"
