name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: "Skip deployment and only print build output"
                default: false
            target-input:
                type: environment
                required: true
                description: Which environment the workflow will target
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: Wich environment the workflow will target



jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tag }}"
            
    
    deploy:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run }}
        environment: ${{ inputs.target-input }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target-input }}"
        